//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntranceLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public int VisitorId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime EntranceDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string VisitTarget { get; set; }
        public string Remark { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
